/*
*   @authors De Andre Powell Mckain, Alvin Alagos Eli, Alexandra Vovc
*   @since 2021-04-19
*   @version 1.0
*
*   Team Project
*   -This is the create schema for our database. All create statements will be allocated here.
*/

CREATE TABLE AIRPORT(
    AIRPORT_ID INT GENERATED ALWAYS AS IDENTITY START WITH 1350 INCREMENT BY 1,
    A_ADDRESS VARCHAR2(50) NOT NULL,
    A_PROVINCE VARCHAR(30) NOT NULL,
    A_PHONENUM CHAR(20) NOT NULL,
    A_POSTALCODE VARCHAR2(10) NOT NULL,
    PRIMARY KEY (AIRPORT_ID));

CREATE TABLE TRAVELER(
    TRAVELER_ID INT GENERATED ALWAYS AS IDENTITY START WITH 10 INCREMENT BY 1,
    T_LNAME VARCHAR(25) NOT NULL,
    T_FNAME VARCHAR(10) NOT NULL,
    T_PHONENUM CHAR(20) NOT NULL,
    T_ADDRESS VARCHAR2(50) NOT NULL,
    PRIMARY KEY (TRAVELER_ID));

CREATE TABLE AIRLINE(
    AIRLINE_ID INT GENERATED ALWAYS AS IDENTITY START WITH 51 INCREMENT BY 1,
    AL_COMPANY VARCHAR(30) NOT NULL,
    AL_PHONENUM CHAR(20) NOT NULL,
    AL_ADDRESS VARCHAR2(50) NOT NULL,
    PRIMARY KEY (AIRLINE_ID));

CREATE TABLE FLIGHT(
    FLIGHT_ID INT GENERATED ALWAYS AS IDENTITY START WITH 20 INCREMENT BY 1,
    F_ROUTE VARCHAR2(30) NOT NULL,
    F_TERMINALNUM VARCHAR2(4) NOT NULL,
    AIRLINE_ID NUMBER(5),
    PRIMARY KEY (FLIGHT_ID),
    CONSTRAINT FK_FLIGHT_AIRPORT
    FOREIGN KEY (AIRLINE_ID) REFERENCES AIRLINE (AIRLINE_ID));

CREATE TABLE AIRPLANE(
    PLANE_ID INT GENERATED ALWAYS AS IDENTITY START WITH 100 INCREMENT BY 1,
    A_CAPACITY CHAR(5) NOT NULL,
    FLIGHT_ID NUMBER(5),
    AIRLINE_ID NUMBER(5),
    PRIMARY KEY (PLANE_ID),
    CONSTRAINT FK_AIRPLANE_FLIGHT
    FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT (FLIGHT_ID),
    CONSTRAINT FK_AIRPLANE_AIRLINE
    FOREIGN KEY (AIRLINE_ID) REFERENCES AIRLINE (AIRLINE_ID));

CREATE TABLE LUGGAGE(
    LUGGAGE_ID INT GENERATED ALWAYS AS IDENTITY START WITH 356 INCREMENT BY 1,
    L_WEIGHT VARCHAR2(5) NOT NULL,
    L_NUMOFLUGGAGE NUMBER NOT NULL,
    TRAVELER_ID NUMBER(5),
    FLIGHT_ID NUMBER(5),
    PRIMARY KEY (LUGGAGE_ID),
    CONSTRAINT FK_LUGGAGE_TRAVELER
    FOREIGN KEY (TRAVELER_ID) REFERENCES TRAVELER (TRAVELER_ID),
    CONSTRAINT FK_LUGGAGE_FLIGHT
    FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT (FLIGHT_ID));

CREATE TABLE TICKET(
    TICKET_ID INT GENERATED ALWAYS AS IDENTITY START WITH 1000 INCREMENT BY 5,
    TRAVELER_ID NUMBER(5),
    AIRLINE_ID NUMBER(5),
    FLIGHT_ID NUMBER(5),
    PRIMARY KEY (TICKET_ID),
    CONSTRAINT FK_TICKET_TRAVELER
    FOREIGN KEY (TRAVELER_ID) REFERENCES TRAVELER (TRAVELER_ID),
    CONSTRAINT FK_TICKET_AIRLINE
    FOREIGN KEY (AIRLINE_ID) REFERENCES AIRLINE (AIRLINE_ID),
    CONSTRAINT FK_TICKET_FLIGHT
    FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT (FLIGHT_ID));

CREATE TABLE AIRPORTAGENT(
    AIRPORTAGENT_ID INT GENERATED ALWAYS AS IDENTITY START WITH 2350 INCREMENT BY 1,
    AA_LNAME VARCHAR(25) NOT NULL,
    AA_FNAME VARCHAR(10) NOT NULL,
    TICKET_ID NUMBER(5),
    AIRPORT_ID NUMBER(5),
    PRIMARY KEY (AIRPORTAGENT_ID),
    CONSTRAINT FK_AIRPORTAGENT_TICKET
    FOREIGN KEY (TICKET_ID) REFERENCES TICKET (TICKET_ID),
    CONSTRAINT FK_AIRPORTAGENT_AIRPORT
    FOREIGN KEY (AIRPORT_ID) REFERENCES AIRPORT (AIRPORT_ID));

CREATE TABLE BOARDINGPASS(
    B_BOARDINGPASS_ID INT GENERATED ALWAYS AS IDENTITY START WITH 1950 INCREMENT BY 1,
    B_DATEISSUED DATE NOT NULL,
    B_TRAVELDATE DATE NOT NULL,
    B_CLASSTYPE VARCHAR(10) NOT NULL,
    AIRPORT_ID NUMBER(5),
    TRAVELER_ID NUMBER(5),
    CONSTRAINT FK_BOARDINGPASS_AIRPORT
    FOREIGN KEY (AIRPORT_ID) REFERENCES AIRPORT (AIRPORT_ID),
    CONSTRAINT FK_BOARDINGPASS_TRAVELER
    FOREIGN KEY (TRAVELER_ID) REFERENCES TRAVELER (TRAVELER_ID));

CREATE TABLE PILOT(
    PILOT_ID INT GENERATED ALWAYS AS IDENTITY START WITH 3000 INCREMENT BY 1,
    P_LNAME VARCHAR(25) NOT NULL,
    P_FNAME VARCHAR(10) NOT NULL,
    P_AGE NUMBER(2), 
    P_YEARSOFSERVICE NUMBER(5),
    PLANE_ID NUMBER(5),
    CONSTRAINT FK_PILOT_AIRPLANE
    FOREIGN KEY (PLANE_ID) REFERENCES AIRPLANE (PLANE_ID));

CREATE TABLE HOTEL(
    HOTEL_ID INT GENERATED ALWAYS AS IDENTITY START WITH 950 INCREMENT BY 1,
    H_ROOMNUM VARCHAR2(4) NOT NULL,
    H_ADDRESS VARCHAR2(30) NOT NULL,
    H_PHONENUM CHAR(20) NOT NULL,
    TRAVELER_ID NUMBER(5),
    CONSTRAINT FK_HOTEL_TRAVELER
    FOREIGN KEY (TRAVELER_ID) REFERENCES TRAVELER (TRAVELER_ID));

