--DELETE TRIGGER
-- Execute Delete, Update, Insert.
SELECT * FROM AIRPLANE;

DELETE AIRPLANE WHERE A_CAPACITY = 500;
--END;

SELECT * FROM FLIGHT;

UPDATE FLIGHT SET F_ROUTE = 'London, England' WHERE FLIGHT_ID = 26;